
spring:
  prifiles:
    active:
      - dev
---
spring:
  prifiles: dev
  application:
    name: microservicecloud-config-ddd-dev
---
spring:
  prifiles: test
  application:
    name: microservicecloud-config-ddd-test

    